
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ahmed
 */
public class LibrarianSection extends javax.swing.JFrame {

    /**
     * Creates new form LibrarianSection
     */
    public LibrarianSection() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        AddBooksButton = new javax.swing.JButton();
        ViewBooksButton = new javax.swing.JButton();
        IssueBookButton = new javax.swing.JButton();
        ViewIssuedBooksButton = new javax.swing.JButton();
        ReturnBooksButton = new javax.swing.JButton();
        LogoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Librarian Section");

        AddBooksButton.setText("Add Books");
        AddBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBooksButtonActionPerformed(evt);
            }
        });

        ViewBooksButton.setText("View Books");
        ViewBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBooksButtonActionPerformed(evt);
            }
        });

        IssueBookButton.setText("Issue Book");
        IssueBookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IssueBookButtonActionPerformed(evt);
            }
        });

        ViewIssuedBooksButton.setText("View Issued Books");
        ViewIssuedBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewIssuedBooksButtonActionPerformed(evt);
            }
        });

        ReturnBooksButton.setText("Return Books");
        ReturnBooksButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnBooksButtonActionPerformed(evt);
            }
        });

        LogoutButton.setText("Logout");
        LogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                .addGap(155, 155, 155))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ViewBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(IssueBookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ViewIssuedBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(ReturnBooksButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LogoutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(143, 143, 143))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(AddBooksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewBooksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IssueBookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ViewIssuedBooksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReturnBooksButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LogoutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IssueBookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IssueBookButtonActionPerformed
        try {
            issuedBook r=new issuedBook();
            r.setVisible(true);
            this.setVisible(false);
        } catch (ParseException ex) {
            Logger.getLogger(LibrarianSection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_IssueBookButtonActionPerformed

    private void LogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutButtonActionPerformed
        LibraryMangment l=new LibraryMangment();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_LogoutButtonActionPerformed

    private void AddBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBooksButtonActionPerformed
        try {
            AddBooks a =new AddBooks();
            a.setVisible(true);
            this.setVisible(false);
        } catch (ParseException ex) {
            Logger.getLogger(LibrarianSection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_AddBooksButtonActionPerformed

    private void ReturnBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnBooksButtonActionPerformed
        try {
            ReturnBooks r=new ReturnBooks();
            r.setVisible(true);
            this.setVisible(false);
        } catch (ParseException ex) {
            Logger.getLogger(LibrarianSection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ReturnBooksButtonActionPerformed

    private void ViewIssuedBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewIssuedBooksButtonActionPerformed
        try {
            ViewIssuedBooks v=new ViewIssuedBooks();
            v.setVisible(true);
            this.setVisible(false);
        } catch (ParseException ex) {
            Logger.getLogger(LibrarianSection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ViewIssuedBooksButtonActionPerformed

    private void ViewBooksButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBooksButtonActionPerformed
        // TODO add your handling code here:
        try {
            ViewBooks r=new ViewBooks();
            r.setVisible(true);
            this.setVisible(false);
        } catch (ParseException ex) {
            Logger.getLogger(LibrarianSection.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ViewBooksButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBooksButton;
    private javax.swing.JButton IssueBookButton;
    private javax.swing.JButton LogoutButton;
    private javax.swing.JButton ReturnBooksButton;
    private javax.swing.JButton ViewBooksButton;
    private javax.swing.JButton ViewIssuedBooksButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
